name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: amd64
            runner: ubuntu-latest
            goos: linux
            goarch: amd64
            out: PDFToolbox-linux-amd64
          - os: linux
            arch: arm64
            runner: ubuntu-latest
            goos: linux
            goarch: arm64
            out: PDFToolbox-linux-arm64
          - os: windows
            arch: amd64
            runner: windows-latest
            goos: windows
            goarch: amd64
            out: PDFToolbox-windows-amd64.exe
            ldflags: -H windowsgui
          - os: macos
            arch: arm64
            runner: macos-latest
            goos: darwin
            goarch: arm64
            out: PDFToolbox-mac-arm64
          - os: macos
            arch: amd64
            runner: macos-13
            goos: darwin
            goarch: amd64
            out: PDFToolbox-mac-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: false

      - name: Install Linux build deps (GLFW/OpenGL)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xorg-dev \
            libgl1-mesa-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxi-dev \
            libxxf86vm-dev \
            libxkbcommon-dev \
            libwayland-dev \
            wayland-protocols

      - name: Go build
        shell: bash
        run: |
          set -euo pipefail
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          mkdir -p dist
          if [[ "${{ matrix.os }}" == "linux" && "${{ matrix.arch }}" == "arm64" ]]; then
            echo "Building Linux arm64 via fyne-cross (Docker)"
            export FYNE_CROSS_IMAGE=fyneio/fyne-cross:latest
            export GOTOOLCHAIN=auto
            GOOS= GOARCH= go run github.com/fyne-io/fyne-cross@v1.6.1 linux -arch arm64 -name PDFToolbox
            # Keep packaged artifact
            cp -f fyne-cross/dist/linux-arm64/PDFToolbox.tar.xz dist/${{ matrix.out }}.tar.xz || true
            # Extract binary and place at expected path
            tar -xJf fyne-cross/dist/linux-arm64/PDFToolbox.tar.xz -C fyne-cross/dist/linux-arm64/
            if [[ -f "fyne-cross/dist/linux-arm64/PDFToolbox" ]]; then
              cp -f fyne-cross/dist/linux-arm64/PDFToolbox dist/${{ matrix.out }}
            else
              BIN_PATH=$(find fyne-cross/dist/linux-arm64 -maxdepth 2 -type f -name PDFToolbox | head -n1)
              if [[ -n "$BIN_PATH" ]]; then cp -f "$BIN_PATH" dist/${{ matrix.out }}; fi
            fi
          else
            export CGO_ENABLED=1
            LD_FLAGS="-s -w ${{ matrix.ldflags }}"
            go build -ldflags="$LD_FLAGS" -o dist/${{ matrix.out }} .
          fi

      - name: Archive artifact
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist
          cd dist
          tar -czf ${{ matrix.out }}.tar.gz ${{ matrix.out }}

      - name: Archive artifact (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          7z a dist/${{ matrix.out }}.zip dist/${{ matrix.out }}

      - name: Upload artifact (non-Windows)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out }}
          path: |
            dist/${{ matrix.out }}
            dist/${{ matrix.out }}.tar.gz

      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out }}
          path: |
            dist/${{ matrix.out }}
            dist/${{ matrix.out }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create GitHub Release (tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create/Update Latest Release (main)
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          prerelease: false
          make_latest: true
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


